// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace NathcorpWebsite.Feature
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Nathcorp")]
    public partial class NathcorpFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Nathcorp.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Nathcorp", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 3
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "URL1"});
            table1.AddRow(new string[] {
                        "https://www.nathcorp.com/"});
#line 4
testRunner.Given(": I Launch the Application", ((string)(null)), table1, "Given ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify Who we are")]
        public virtual void VerifyWhoWeAre()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify Who we are", null, ((string[])(null)));
#line 9
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 3
this.FeatureBackground();
#line 10
  testRunner.When("I click on Who we are", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 11
  testRunner.Then("User should be redirected to who we are page in same window", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify Who we Do it for")]
        public virtual void VerifyWhoWeDoItFor()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify Who we Do it for", null, ((string[])(null)));
#line 14
  this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 3
this.FeatureBackground();
#line 15
  testRunner.When("I click on Who we Do it for", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 16
  testRunner.Then("User Should be redirected to Who we Do it for page in same window", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify that User is able to hover the Services link and able to click on Active D" +
            "irectory link.")]
        public virtual void VerifyThatUserIsAbleToHoverTheServicesLinkAndAbleToClickOnActiveDirectoryLink_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify that User is able to hover the Services link and able to click on Active D" +
                    "irectory link.", null, ((string[])(null)));
#line 18
  this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 3
this.FeatureBackground();
#line 19
  testRunner.When("I Hover on Services link.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 20
  testRunner.Then("The List of service menu should appear", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 21
  testRunner.And("I Click on Active Directory link.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 22
  testRunner.Then("Active Directory page should appear.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify that user is able to hover the Services link and able to click on App Mode" +
            "rnization link.")]
        public virtual void VerifyThatUserIsAbleToHoverTheServicesLinkAndAbleToClickOnAppModernizationLink_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify that user is able to hover the Services link and able to click on App Mode" +
                    "rnization link.", null, ((string[])(null)));
#line 24
  this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 3
this.FeatureBackground();
#line 25
  testRunner.When("I Hover on Services1 link.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 26
  testRunner.Then("The list of service1 menu should appear.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 27
  testRunner.And("I click on App Modernization link.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 28
  testRunner.Then("Application Modernization page should appear.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify that user is able to hover the Services link and able to click on Cloud En" +
            "ablement link.")]
        public virtual void VerifyThatUserIsAbleToHoverTheServicesLinkAndAbleToClickOnCloudEnablementLink_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify that user is able to hover the Services link and able to click on Cloud En" +
                    "ablement link.", null, ((string[])(null)));
#line 30
  this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 3
this.FeatureBackground();
#line 31
  testRunner.When("I Hover on Service link.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 32
  testRunner.Then("The list of servic menu should appear.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 33
  testRunner.And("I click on Cloud Enablement link.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 34
  testRunner.Then("Cloud Enablement page should appear.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify that user is able to hover the Services link and able to click on Managed " +
            "Services link.")]
        public virtual void VerifyThatUserIsAbleToHoverTheServicesLinkAndAbleToClickOnManagedServicesLink_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify that user is able to hover the Services link and able to click on Managed " +
                    "Services link.", null, ((string[])(null)));
#line 36
  this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 3
this.FeatureBackground();
#line 37
  testRunner.When("I Hover on Service linkk.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 38
  testRunner.Then("The list of servic menu shouldd appear.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 39
  testRunner.And("I click on Managed Services linkk.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 40
  testRunner.Then("Managed Services page should apppear.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify that user is able to hover the Services link and able to click on Modern D" +
            "eployment link.")]
        public virtual void VerifyThatUserIsAbleToHoverTheServicesLinkAndAbleToClickOnModernDeploymentLink_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify that user is able to hover the Services link and able to click on Modern D" +
                    "eployment link.", null, ((string[])(null)));
#line 42
   this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 3
this.FeatureBackground();
#line 43
  testRunner.When("I Hoverr on Service linkk.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 44
  testRunner.Then("The listt of servic menu shouldd appear.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 45
  testRunner.And("I clickk on Modern Deployment linkk.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 46
  testRunner.Then("Modern Deployment page should apppear.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify that user is able to hover the Services link and able to click on Security" +
            " link.")]
        public virtual void VerifyThatUserIsAbleToHoverTheServicesLinkAndAbleToClickOnSecurityLink_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify that user is able to hover the Services link and able to click on Security" +
                    " link.", null, ((string[])(null)));
#line 48
    this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 3
this.FeatureBackground();
#line 49
  testRunner.When("I Hoverr on Servicee linkk.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 50
  testRunner.Then("The listt of servic menu shouldd appearr.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 51
  testRunner.And("I clickk on Security linkk.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 52
  testRunner.Then("Security page should apppear.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify that user is able to hover the Services link and able to click on Teams an" +
            "d Collaboration link.")]
        public virtual void VerifyThatUserIsAbleToHoverTheServicesLinkAndAbleToClickOnTeamsAndCollaborationLink_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify that user is able to hover the Services link and able to click on Teams an" +
                    "d Collaboration link.", null, ((string[])(null)));
#line 54
   this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 3
this.FeatureBackground();
#line 55
  testRunner.When("I Hoverr onn Servicee linkk.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 56
  testRunner.Then("The listt off servic menu shouldd appearr.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 57
  testRunner.And("I clickk on Teams and Collaboration linkk.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 58
  testRunner.Then("Teams and Collaboration page should apppear.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify that user is able to hover the Services link and able to click on Emerging" +
            " Technologies link.")]
        public virtual void VerifyThatUserIsAbleToHoverTheServicesLinkAndAbleToClickOnEmergingTechnologiesLink_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify that user is able to hover the Services link and able to click on Emerging" +
                    " Technologies link.", null, ((string[])(null)));
#line 60
   this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 3
this.FeatureBackground();
#line 61
  testRunner.When("I Hoverr onn Servicee linkkk.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 62
  testRunner.Then("The listt off service menu shouldd appearr.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 63
  testRunner.And("I clickk on Teams and Emerging Technologies.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 64
  testRunner.Then("Emerging Technologies page should apppear.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify that User is able to click on Service link.")]
        public virtual void VerifyThatUserIsAbleToClickOnServiceLink_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify that User is able to click on Service link.", null, ((string[])(null)));
#line 66
   this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 3
this.FeatureBackground();
#line 67
  testRunner.When("I click on Service link.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 68
  testRunner.Then("User Should be redirected to What we Do  page.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify that User is able to click on Product link.")]
        public virtual void VerifyThatUserIsAbleToClickOnProductLink_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify that User is able to click on Product link.", null, ((string[])(null)));
#line 70
   this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 3
this.FeatureBackground();
#line 71
  testRunner.When("I click on Product link.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 72
  testRunner.Then("User Should be redirected to Modern deployment page.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify that user is able to hover the Product link and able to click on Docsync l" +
            "ink.")]
        public virtual void VerifyThatUserIsAbleToHoverTheProductLinkAndAbleToClickOnDocsyncLink_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify that user is able to hover the Product link and able to click on Docsync l" +
                    "ink.", null, ((string[])(null)));
#line 74
    this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 3
this.FeatureBackground();
#line 75
  testRunner.When("I Hover on Product link.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 76
  testRunner.Then("The list of Product menu should appear.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 77
  testRunner.And("I click on  Docsync link.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 78
  testRunner.Then("Docsync page should apppear.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify that user is able to hover the Product link and able to click on Teams Tem" +
            "po link.")]
        public virtual void VerifyThatUserIsAbleToHoverTheProductLinkAndAbleToClickOnTeamsTempoLink_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify that user is able to hover the Product link and able to click on Teams Tem" +
                    "po link.", null, ((string[])(null)));
#line 80
   this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 3
this.FeatureBackground();
#line 81
  testRunner.When("I Hover on Product linkk.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 82
  testRunner.Then("The list of Product menu shouldd appear.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 83
  testRunner.And("I click on  Teams Tempo link.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 84
  testRunner.Then("Teams Tempo page should apppear.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify that user is able to hover the Product link and able to click on M365 Gove" +
            "rnance Manager link.")]
        public virtual void VerifyThatUserIsAbleToHoverTheProductLinkAndAbleToClickOnM365GovernanceManagerLink_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify that user is able to hover the Product link and able to click on M365 Gove" +
                    "rnance Manager link.", null, ((string[])(null)));
#line 86
   this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 3
this.FeatureBackground();
#line 87
  testRunner.When("I Hover on Productt linkk.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 88
  testRunner.Then("The listt of Product menu shouldd appear.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 89
  testRunner.And("I click on  M365 Governance Manager.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 90
  testRunner.Then("M365 Governance Manager page should apppear.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify Why People Use Us page.")]
        [NUnit.Framework.CategoryAttribute("Verify")]
        [NUnit.Framework.CategoryAttribute("Why")]
        [NUnit.Framework.CategoryAttribute("People")]
        [NUnit.Framework.CategoryAttribute("Use")]
        [NUnit.Framework.CategoryAttribute("Uss")]
        [NUnit.Framework.CategoryAttribute("page.")]
        public virtual void VerifyWhyPeopleUseUsPage_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify Why People Use Us page.", null, new string[] {
                        "Verify",
                        "Why",
                        "People",
                        "Use",
                        "Uss",
                        "page."});
#line 93
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 3
this.FeatureBackground();
#line 94
  testRunner.When("I click on Why People Use Us page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 95
  testRunner.Then("User Should be redirected to  Why People Use Us page in same window", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify Working AT Nathcorp page.")]
        public virtual void VerifyWorkingATNathcorpPage_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify Working AT Nathcorp page.", null, ((string[])(null)));
#line 97
   this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 3
this.FeatureBackground();
#line 98
  testRunner.When("I click on Working AT Nathcorp page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 99
   testRunner.Then("User Should be redirected to Careers page in same window", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify Contact Us page.")]
        public virtual void VerifyContactUsPage_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify Contact Us page.", null, ((string[])(null)));
#line 102
   this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 3
this.FeatureBackground();
#line 103
  testRunner.When("I click on Contact Us page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 104
   testRunner.Then("User Should be redirected to Contact Us page in same window", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify Apply Now page inside Working AT Nathcorp page.")]
        public virtual void VerifyApplyNowPageInsideWorkingATNathcorpPage_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify Apply Now page inside Working AT Nathcorp page.", null, ((string[])(null)));
#line 106
   this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 3
this.FeatureBackground();
#line 107
   testRunner.When("I clickk on Working AT Nathcorp page.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 108
    testRunner.Then("User Should be redirected to Careers page inn same window.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 109
    testRunner.And("I click on Apply Now page.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 110
    testRunner.Then("Nathcorp Apply Now page should open.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify Apply Now page inside Workingg AT Nathcorp page.")]
        [NUnit.Framework.CategoryAttribute("ApplyNow")]
        [NUnit.Framework.TestCaseAttribute("Ritesh", "Ranjan", "ritesh8200@gmail.com", "1234567890", "1234567890", "Garhwa", "Garhwa", "jharkhand", "822128", "India", new string[] {
                "source:Applynowsheet.xlsx:sheet1"}, Category="source:Applynowsheet.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("Rohan", "kumar", "Rohan8200@gmail.com", "1234567890", "1234567890", "Garhwa", "Garhwa", "jharkhand", "822180", "India", new string[] {
                "source:Applynowsheet.xlsx:sheet1"}, Category="source:Applynowsheet.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("Shyam", "kumar", "Shyam8200@gmail.com", "1234567890", "1234567890", "Garhwa", "Garhwa", "jharkhand", "831012", "India", new string[] {
                "source:Applynowsheet.xlsx:sheet1"}, Category="source:Applynowsheet.xlsx:sheet1")]
        public virtual void VerifyApplyNowPageInsideWorkinggATNathcorpPage_(string firstName, string lastName, string email, string homePhone, string mobilePhone, string address, string city, string state, string zip, string country, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "ApplyNow"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify Apply Now page inside Workingg AT Nathcorp page.", null, @__tags);
#line 113
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 3
this.FeatureBackground();
#line 114
     testRunner.When("I clickk on Working AT Nathcorp pagee.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 115
     testRunner.Then("User Should be redirected to Careers page inn samee window.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 116
     testRunner.And("I click onn Apply Now page.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 117
     testRunner.Then("Nathcorpp Apply Now page should open.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 118
     testRunner.And(string.Format("user should enter the First Name {0},Last Name {1},Email {2},Home Phone {3},Mobil" +
                        "e Phone {4},Address {5},City {6},State{7},Zip{8},Country{9}", firstName, lastName, email, homePhone, mobilePhone, address, city, state, zip, country), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 119
     testRunner.Then("select the Employment Desired.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 120
     testRunner.And("Select the resume in proper format.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 121
     testRunner.Then("Click on Submit button.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify Contact Us page at Nathcorp page.")]
        [NUnit.Framework.CategoryAttribute("ContactUs")]
        [NUnit.Framework.TestCaseAttribute("Ritesh", "riteshranjan8200@gmail.com", "Nathcorp", "123456789", "hi how r u.", new string[] {
                "source:ContactUs.xlsx:sheet1"}, Category="source:ContactUs.xlsx:sheet1")]
        public virtual void VerifyContactUsPageAtNathcorpPage_(string name, string email, string company, string phone, string message, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "ContactUs"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify Contact Us page at Nathcorp page.", null, @__tags);
#line 127
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 3
this.FeatureBackground();
#line 128
       testRunner.When("I click on Contact Us page.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 129
       testRunner.Then("We are here to help page should open.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 130
       testRunner.And(string.Format("User should enter the Name{0},Email{1},Company{2},Phone{3},Message{4}.", name, email, company, phone, message), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 131
       testRunner.Then("Click on Send Message.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
